config/routes.rb
Rails.application.routes.draw do
  root 'todos#index'
  
  resources :categories
  # routes => 通信(GET,POST,etc..)をどのコントローラのどのアクションで処理するか分配
  # [参考]https://railsguides.jp/routing.html#%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%83%99%E3%83%BC%E3%82%B9%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0-rails%E3%81%AE%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88
  resources :todos do  # 「todosコントローラ」をcall（7つのアクション(上記URL参照)）
    member do
      patch 'status' # 状態を変更 => ptach(部分) or put(全体)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # リレーション完了(todo.rb->belongs_to: categories)
    has_many :todos
    
    validates :name, presence: true
end

app/models/todo.rb
class Todo < ApplicationRecord
    # リレーション：Todoモデルーtodosテーブル(ActiveRecored)
    # todosテーブルに「titleカラム」がある → Todoモデルで「titleメソッド」としてcall
    
    # リレーション完了(category.rb->has_many :todos)
    # todo.category.nameなどができる => todoと関連付いたcategoryモデルのnameを取得
    belongs_to :category 
    
    # varidation
    validates :title, presence: true
    validates :detail, presence: true
    validates :priority, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # before_action :action名, only: [:action名1, :action名2, ...]
  # before_action :action名  =>  actionの前にcall
  # only: [:action名1, :action名2, ...]  =>  ここで指定したactionの前にbefore_actionがcall
  before_action :set_todo, only: [:show, :edit, :update, :status, :destroy]

  # GET /todos
  # GET /todos.json
  # '/'でtodosコントローラーが叩かれてindexアクションがcallされる
  # => '$ bin/rails routes'で確認
  def index
    # [参考][pagenation]https://teratail.com/questions/63813
    @todos = Todo.where(status: 0).order(priority: "DESC").page params[:page] #インスタンス変数@todosを使っているのは、後でviewで利用するため(複数形)　#[参考]http://igarashikuniaki.net/rails_textbook/crud.html
    # sinatraで言う「erb :index」がない...
    # =>「views > todos > index.html.erb」を探してくれる
    # つまり、'Controller'xxxアクションがcallされるとデフォルトで'views'xxx.html.erbをrender
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    # =>「views > todos > show.html.erb」を探してくれる
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params) # @todo(インスタンス変数)=>Railsの場合は、1つのリクエスト内が有効範囲だと考えれる(redirect_toは有効範囲外)

    # TODO:respond_toとは？
    respond_to do |format|
      if @todo.save
        # 'format.html','format.json'は拡張子を表す(例：format.html{...} => 「formatがhtmlの場合は...」みたいな)
        # TODO:'@todo'インスタンスだけ渡す→対応したshowアクションが呼び出される?renderが呼び出される？
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
        # [renderとrefirect_to]https://qiita.com/1ulce/items/282cccba1e44158489c8
        # [renderとrefirect_to(図解)]http://igarashikuniaki.net/rails_textbook/new-create.html
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      # @todoをいきなり使ってる => before_actionでset_todoアクションが先に呼ばれる為
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # [追加アクション]PATCH /todos/1/status (→routes.rb)
  def status
    @todo.status = params[:status]
    @todo.save!
    redirect_to root_url, notice: "「#{@todo.title}」を完了しました！" #root_url => idnexへ飛ばす
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      # Todo(model名(ActiveRecord)⇄tabel名(DB))からprams[:id]をfind
      @todo = Todo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      # データを取得
      # セキュリティの為の機能(Strong Parameters)
        # paramsに入ってくる値を指定（それ以外入るとerror => Unpermitted parameter: xxx）
      params.require(:todo).permit(:title, :detail, :status, :priority, :category_id)
      # ===== params.require(:todo).permit(:title, :detail, :status)とは？ =====
      # params[:todo] = {title: "first", details: "詳細", status: 1}みたいなをそれぞれ「データ取得」
      # params[:todo][:title] # => "first"
      # => params.require(:モデル名).permit(:カラム名1, :カラム名2, ...)
      # [関連]「form_for」(views>todos>_form.html.erb)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <!-- ===== error ===== -->
  <%= render 'shared/errors', todo: category %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

<%= render 'todos/todos_table', todos: @category.todos %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO app</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'TODO app', root_path, class: "link" %></h1> <!-- todos_pathと同じ(routes.rbで設定) -->
    
    <div id="wrapper" class="todo">
      <div class="todo__add">
        <%= link_to 'TODO一覧', todos_path %>
        <%= link_to 'TODOを追加する', new_todo_path %>
        <%= link_to 'カテゴリー一覧', categories_path %>
        <%= link_to 'カテゴリーを追加する', new_category_path %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<!-- ===== error ===== -->
<% if todo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(todo.errors.count, "個") %> のエラーがあります。:</h2>

  <ul>
  <% todo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %> <!-- https://qiita.com/hmmrjn/items/24f3b8eade206ace17e2 -->
  <!-- ===== error ===== -->
  <%= render 'shared/errors', todo: todo %>

  <!-- ===== form ===== -->
  <div class="field">
    <!-- form.xxx -> xxxはformのビルドヘルパーと言うらしい -->
    <!-- => for="todo_title" -->
    <%= form.label :title %>
    <!-- => name="todo[title]" id="todo_title" -->
    <!-- nameに入っている名前でデータを飛ばす(name="xxx"のxxx部分) -->
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>
  
  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>
  
  <div class="field">
    <%= form.label :category_id %>
    <!-- TODO:controllerに記述 -->
    <% @categories = Category.all %><%= form.select :category_id, @categories.map{|category| [category.name, category.id]}, {include_blank: true}, class: 'categories' %> <!-- https://shinmedia20.com/rails-select-box -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todos_table.html.erb
<%= paginate todos %>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Detail</th>
      <th>priority</th>
      <th>category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% todos.each do |todo| %> <!-- localsに値を渡した -->
      <tr>
        <!-- 「todo」だけで「todo.id」 を使って、 「todos/:id」というパスを自動的に作成 -->
        <td><%= link_to todo do %><%= todo.title %><% end %></td> <!-- polymorphic_path機能 --><!-- todo_path(todo)と同じ意味 -->
        <td><%= todo.detail %></td>
        <td><%= todo.priority %></td>
        <td><%= todo.category.try(:name) %></td> <!-- categoryを指定されていない場合もある->合ったときだけ表示したい->try(:xxx) -->
        <td><%= link_to '完了', status_todo_path(todo, status: 1), method: :patch %></td> <!-- [imp.]「method: :HTTP通信名」で通信方法を指定できる --><!-- hashをparamsとして自由に送れる -->
        <td><%= link_to '編集', edit_todo_path(todo) %></td> <!-- [imp.]todoにはtodo.idがautoで入る -->
        <td><%= link_to '削除', todo, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>ToDo一覧</h1>

<%= render 'todos_table', todos: @todos %>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<!-- render 'form' => _form.html.erb -->
<!-- 'render 埋め込みたいファイル名, パーシャル内で使う変数名: 渡す変数'  -->
<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @todo.detail %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @todo.priority %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>